package com.vinculacion.app.views;

import java.awt.Color;
import java.awt.Frame;
import javax.swing.JFrame;

public class MenuPrincipal extends javax.swing.JFrame {

    public MenuPrincipal() {
        initComponents();
        setExtendedState(Frame.MAXIMIZED_BOTH);     
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setTitle("Sistema de Gestión de pasantías SGP"); 
        
        Color colorfondo = new Color(Iconos.hex("f1f5f1"));
        this.getContentPane().setBackground(colorfondo);
        Iconos.setLogo(this);
        this.menuItemNomUser.setForeground(Color.RED);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuItemNomUser = new javax.swing.JMenuItem();
        menuItemListadoDocentes = new javax.swing.JMenuItem();
        menuItemListadoPasantes = new javax.swing.JMenuItem();
        menuItemListadoEmpresas = new javax.swing.JMenuItem();
        menuItemCerrar = new javax.swing.JMenuItem();
        menuItemSalir = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuItemTipoDocPracticas = new javax.swing.JMenuItem();
        menuItemEmpresa = new javax.swing.JMenuItem();
        menuItemDepartamento = new javax.swing.JMenuItem();
        menuItemCargoDepartamental = new javax.swing.JMenuItem();
        menuItemEmpleados = new javax.swing.JMenuItem();
        menuItemHorarioPasantias = new javax.swing.JMenuItem();
        menuItemPasante = new javax.swing.JMenuItem();
        menuItemPasantia = new javax.swing.JMenuItem();
        menuItemInforme = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuUtb = new javax.swing.JMenu();
        menuItemFacultad = new javax.swing.JMenuItem();
        menuItemEscuelas = new javax.swing.JMenuItem();
        menuItemCarreras = new javax.swing.JMenuItem();
        menuItemTipoDedicacionDocente = new javax.swing.JMenuItem();
        menuItemDocentes = new javax.swing.JMenuItem();
        menuItemAsignaturas = new javax.swing.JMenuItem();
        menuItemCargosDocentes = new javax.swing.JMenuItem();
        menuItemNivel = new javax.swing.JMenuItem();
        menuItemPeriodosAcademicos = new javax.swing.JMenuItem();
        menuItemGenero = new javax.swing.JMenuItem();
        menuItemSeccion = new javax.swing.JMenuItem();
        menuItemUsuarios = new javax.swing.JMenuItem();
        menuItemPerfil = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuArchivo.setText("Archivo");

        menuItemNomUser.setText("user");
        menuArchivo.add(menuItemNomUser);

        menuItemListadoDocentes.setText("Generar listado de docentes");
        menuArchivo.add(menuItemListadoDocentes);

        menuItemListadoPasantes.setText("Generar listado de pasantes");
        menuArchivo.add(menuItemListadoPasantes);

        menuItemListadoEmpresas.setText("Generar listado de empresas donde los alumnos hayan realizados sus prácticas");
        menuArchivo.add(menuItemListadoEmpresas);

        menuItemCerrar.setText("Cerrar");
        menuArchivo.add(menuItemCerrar);

        menuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        menuItemSalir.setText("Salir");
        menuArchivo.add(menuItemSalir);

        jMenuBar1.add(menuArchivo);

        jMenu5.setText("Pasantías");

        menuItemTipoDocPracticas.setText("Tipo de documento de prácticas");
        jMenu5.add(menuItemTipoDocPracticas);

        menuItemEmpresa.setText("Empresa");
        jMenu5.add(menuItemEmpresa);

        menuItemDepartamento.setText("Departamentos");
        jMenu5.add(menuItemDepartamento);

        menuItemCargoDepartamental.setText("Cargos departamentales");
        jMenu5.add(menuItemCargoDepartamental);

        menuItemEmpleados.setText("Empleados");
        jMenu5.add(menuItemEmpleados);

        menuItemHorarioPasantias.setText("Horario de pasantías");
        jMenu5.add(menuItemHorarioPasantias);

        menuItemPasante.setText("Pasante");
        jMenu5.add(menuItemPasante);

        menuItemPasantia.setText("Pasantía");
        jMenu5.add(menuItemPasantia);

        menuItemInforme.setText("Informe de pasantías");
        jMenu5.add(menuItemInforme);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Mantenimiento");

        menuUtb.setText("UTB");

        menuItemFacultad.setText("Facultad");
        menuItemFacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFacultadActionPerformed(evt);
            }
        });
        menuUtb.add(menuItemFacultad);

        menuItemEscuelas.setText("Escuelas");
        menuUtb.add(menuItemEscuelas);

        menuItemCarreras.setText("Carreras");
        menuUtb.add(menuItemCarreras);

        jMenu2.add(menuUtb);

        menuItemTipoDedicacionDocente.setText("Tipo de dedicación del docente");
        jMenu2.add(menuItemTipoDedicacionDocente);

        menuItemDocentes.setText("Docentes");
        jMenu2.add(menuItemDocentes);

        menuItemAsignaturas.setText("Asignaturas");
        jMenu2.add(menuItemAsignaturas);

        menuItemCargosDocentes.setText("Cargos de los docentes");
        menuItemCargosDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCargosDocentesActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemCargosDocentes);

        menuItemNivel.setText("Niveles académicos");
        menuItemNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNivelActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemNivel);

        menuItemPeriodosAcademicos.setText("Periodos Académicos");
        jMenu2.add(menuItemPeriodosAcademicos);

        menuItemGenero.setText("Generos");
        menuItemGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGeneroActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemGenero);

        menuItemSeccion.setText("Sección");
        jMenu2.add(menuItemSeccion);

        menuItemUsuarios.setText("Usuarios");
        jMenu2.add(menuItemUsuarios);

        menuItemPerfil.setText("Perfil");
        jMenu2.add(menuItemPerfil);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1315, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemFacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFacultadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemFacultadActionPerformed

    private void menuItemNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemNivelActionPerformed

    private void menuItemGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemGeneroActionPerformed

    private void menuItemCargosDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCargosDocentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemCargosDocentesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenu menuArchivo;
    public javax.swing.JMenuItem menuItemAsignaturas;
    public javax.swing.JMenuItem menuItemCargoDepartamental;
    public javax.swing.JMenuItem menuItemCargosDocentes;
    public javax.swing.JMenuItem menuItemCarreras;
    public javax.swing.JMenuItem menuItemCerrar;
    public javax.swing.JMenuItem menuItemDepartamento;
    public javax.swing.JMenuItem menuItemDocentes;
    public javax.swing.JMenuItem menuItemEmpleados;
    public javax.swing.JMenuItem menuItemEmpresa;
    public javax.swing.JMenuItem menuItemEscuelas;
    public javax.swing.JMenuItem menuItemFacultad;
    public javax.swing.JMenuItem menuItemGenero;
    public javax.swing.JMenuItem menuItemHorarioPasantias;
    public javax.swing.JMenuItem menuItemInforme;
    public javax.swing.JMenuItem menuItemListadoDocentes;
    public javax.swing.JMenuItem menuItemListadoEmpresas;
    public javax.swing.JMenuItem menuItemListadoPasantes;
    public javax.swing.JMenuItem menuItemNivel;
    public javax.swing.JMenuItem menuItemNomUser;
    public javax.swing.JMenuItem menuItemPasante;
    public javax.swing.JMenuItem menuItemPasantia;
    public javax.swing.JMenuItem menuItemPerfil;
    public javax.swing.JMenuItem menuItemPeriodosAcademicos;
    public javax.swing.JMenuItem menuItemSalir;
    public javax.swing.JMenuItem menuItemSeccion;
    public javax.swing.JMenuItem menuItemTipoDedicacionDocente;
    public javax.swing.JMenuItem menuItemTipoDocPracticas;
    public javax.swing.JMenuItem menuItemUsuarios;
    public javax.swing.JMenu menuUtb;
    // End of variables declaration//GEN-END:variables
}
